export const mockTeamMembers = [
  { id: '1', name: 'Sarah Chen', role: 'Admin', email: 'sarah@company.com' },
  { id: '2', name: 'Michael Park', role: 'Designer', email: 'michael@company.com' },
  { id: '3', name: 'Emily Rodriguez', role: 'Content Writer', email: 'emily@company.com' },
  { id: '4', name: 'David Kim', role: 'Developer', email: 'david@company.com' },
  { id: '5', name: 'Lisa Thompson', role: 'Reviewer', email: 'lisa@company.com' },
];

export const mockProjects = [
  {
    id: '1',
    projectId: 'IN-GD-ABC-0125-0001',
    clientName: 'ABC Technologies',
    country: 'IN',
    serviceType: 'GD',
    month: 'January',
    year: '2025',
    status: 'In Progress',
    assignedTo: '2',
    internalNotes: 'Client prefers minimalist design approach',
    attachments: [],
    createdAt: new Date('2025-01-05'),
    updatedAt: new Date('2025-01-07'),
    graphicDesign: {
      postType: 'Social Post',
      platform: 'Instagram',
      size: 'Square',
      mainText: 'Launch your business today',
      subText: 'Professional solutions for modern enterprises',
      ctaText: 'Get Started',
      hashtags: '#business #growth #technology',
      designerNotes: 'Use brand colors from guidelines',
    },
  },
  {
    id: '2',
    projectId: 'US-WD-XYZ-0125-0001',
    clientName: 'XYZ Corp',
    country: 'US',
    serviceType: 'WD',
    month: 'January',
    year: '2025',
    status: 'Review',
    assignedTo: '4',
    internalNotes: 'Priority client - fast turnaround needed',
    attachments: [],
    createdAt: new Date('2025-01-03'),
    updatedAt: new Date('2025-01-08'),
    websiteDesign: {
      websiteType: 'Corporate',
      numberOfPages: '6-10',
      technologyPreference: 'React, Next.js',
      referenceWebsites: 'stripe.com, linear.app',
      pages: [
        {
          pageName: 'Home',
          pagePurpose: 'Main landing page with hero and key features',
          sections: [
            {
              sectionType: 'Hero',
              mainHeading: 'Transform Your Business',
              subHeading: 'Enterprise solutions for the modern age',
              paragraphText: 'We help companies scale with cutting-edge technology',
              buttonText: 'Learn More',
              buttonLink: '/about',
              layoutNotes: 'Full-width hero with gradient background',
            },
          ],
        },
      ],
    },
  },
  {
    id: '3',
    projectId: 'CA-CW-DEF-0125-0001',
    clientName: 'DEF Media',
    country: 'CA',
    serviceType: 'CW',
    month: 'January',
    year: '2025',
    status: 'Draft',
    assignedTo: '3',
    internalNotes: 'Need SEO focus for this content',
    attachments: [],
    createdAt: new Date('2025-01-06'),
    updatedAt: new Date('2025-01-06'),
    contentWriting: {
      contentType: 'Blog',
      wordCount: '1500',
      tone: 'Professional',
      mainContent: '',
      cta: 'Subscribe to our newsletter',
      seoKeywords: 'digital marketing, content strategy, SEO',
      reviewNotes: '',
    },
  },
  {
    id: '4',
    projectId: 'UAE-ERP-GHI-0125-0001',
    clientName: 'GHI Industries',
    country: 'UAE',
    serviceType: 'ERP',
    month: 'January',
    year: '2025',
    status: 'Approved',
    assignedTo: '4',
    internalNotes: 'Large-scale manufacturing ERP implementation',
    attachments: [],
    createdAt: new Date('2025-01-02'),
    updatedAt: new Date('2025-01-08'),
    erp: {
      erpType: 'Manufacturing',
      modulesRequired: ['Inventory', 'Production', 'Quality Control', 'Procurement'],
      workflowDescription: 'End-to-end manufacturing workflow with quality gates',
      userRoles: 'Admin, Manager, Operator, QC Inspector',
      integrationsRequired: 'SAP, Salesforce',
      technicalNotes: 'Need to support Arabic language interface',
    },
  },
  {
    id: '5',
    projectId: 'IN-GD-JKL-0125-0001',
    clientName: 'JKL Ventures',
    country: 'IN',
    serviceType: 'GD',
    month: 'January',
    year: '2025',
    status: 'Delivered',
    assignedTo: '2',
    internalNotes: 'Delivered ahead of schedule',
    attachments: [],
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-05'),
    graphicDesign: {
      postType: 'Banner',
      platform: 'Website',
      size: 'Landscape',
      mainText: 'New Year Sale',
      subText: 'Up to 50% off on all products',
      ctaText: 'Shop Now',
      hashtags: '',
      designerNotes: 'Festive theme with vibrant colors',
    },
  },
];